import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.scss";
import ReduxProvider from "./Redux/ReduxProvider";
import Header from "./Header/Header";
import Footer from "./Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Welkin",
   description: "Generated by create next app",
};

const circle = localFont({
   src: [
      {
         path: "../public/fonts/circle/Circe-ExtraBold.ttf",
         weight: "800",
         style: "extraBold",
      },
      {
         path: "../public/fonts/circle/Circe-Bold.ttf",
         weight: "700",
         style: "bold",
      },
      {
         path: "../public/fonts/circle/Circe-Regular.ttf",
         weight: "400",
         style: "normal",
      },
      {
         path: "../public/fonts/circle/Circe-Light.ttf",
         weight: "300",
         style: "light",
      },
      {
         path: "../public/fonts/circle/Circe-ExtraLight.ttf",
         weight: "200",
         style: "extraLight",
      },
      {
         path: "../public/fonts/circle/Circe-Thin.ttf",
         weight: "100",
         style: "thin",
      },
   ],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="ru">
         <body className={circle.className}>
            <div className="wrapper">
               <header className="header">
                  <Header />
               </header>

               <main className="main">
                  <ReduxProvider>{children}</ReduxProvider>
               </main>

               <footer className="footer">
                  <Footer />
               </footer>
            </div>
         </body>
      </html>
   );
}
