import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import ReduxProvider from "./Redux/ReduxProvider";
import Header from "./Header/Header";
import Footer from "./Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Welkin",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="ru">
         <body className={inter.className}>
            <div className="wrapper">
               <header className="header">
                  <Header />
               </header>

               <main className="main">
                  <ReduxProvider>{children}</ReduxProvider>
               </main>

               <footer className="footer">
                  <Footer />
               </footer>
            </div>
         </body>
      </html>
   );
}
